### ISSUE TITLE
Bot.restrictChatMember not working

### ISSUE THREAD

**Issue by YouROK** [kotlin-telegram-bot/kotlin-telegram-bot#104]
**Expected behavior**
working function

**Actual behavior**
not working

**To Reproduce**
newChatMembers { bot, message, list ->
                                val resp = bot.restrictChatMember(
                                    message.chat.id, usr.id, ChatPermissions(
                                        false,
                                        false,
                                        false,
                                        false,
                                        false,
                                        false,
                                        false,
                                        false
                                    ), Date(0)
                                )
}

**Screenshots/Traceback**
сент. 14, 2020 4:56:24 PM okhttp3.internal.platform.Platform log
INFO: chat_id=-***&user_id=***&permissions=ChatPermissions%28canSendMessages%3Dfalse%2C%20canSendMediaMessages%3Dfalse%2C%20canSendPolls%3Dfalse%2C%20canSendOtherMessages%3Dfalse%2C%20canAddWebPagePreviews%3Dfalse%2C%20canChangeInfo%3Dfalse%2C%20canInviteUsers%3Dfalse%2C%20canPinMessages%3Dfalse%29&until_date=Thu%20Jan%2001%2003%3A00%3A00%20MSK%201970
сент. 14, 2020 4:56:24 PM okhttp3.internal.platform.Platform log
INFO: --> END POST (363-byte body)
сент. 14, 2020 4:56:24 PM okhttp3.internal.platform.Platform log
INFO: <-- 400 Bad Request https://api.telegram.org/***/restrictChatMember (89ms)

**Possible solutions**
In docs telegram server have json
https://core.telegram.org/bots/api#restrictchatmember
but sends
ChatPermissions(canSendMessages=false, canSendMediaMessages=false, canSendPolls=false, canSendOtherMessages=false, canAddWebPagePreviews=false, canChangeInfo=false, canInviteUsers=false, canPinMessages=false)&until_date=Thu Jan 01 03:00:00 MSK 1970

**Comment by vjgarciag96** [comment]
I'll take a look to this issue, thanks for the report!

**Comment by YouROK** [comment]
with this patch working ok
[0001-fix-user-restrict.patch.txt](https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/files/5224204/0001-fix-user-restrict.patch.txt)

**Comment by vjgarciag96** [comment]
Fixed with https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/109
