### ISSUE TITLE
Abnormal errorMessage returned by getUpdates

### ISSUE THREAD

**Issue by reopold** [kotlin-telegram-bot/kotlin-telegram-bot#114]
**Expected behavior**
In case of an error in the process of receiving updates, we would like to receive a response from the server, like:
_{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}_

**Actual behavior**
Now we get:
_serverResponse = okhttp3.ResponseBody$1@7fe86edf_

**To Reproduce**
Run two instances of the bot.

**Comment by vjgarciag96** [comment]
Fixed in https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/115
