### ISSUE TITLE
chatId in sends commands may by Long or String

### ISSUE THREAD

**Issue by YouROK** [kotlin-telegram-bot/kotlin-telegram-bot#117]
To send messages, we can use a number or a string to chat or channel.
But to send to a channel, we usually use the channel name and the channel id is unknown.
The api telegram says that chatId 

> chat_id | Integer or String | Yes | Unique identifier for the target chat or username of the target channel (in the format _@channelusername_)

https://core.telegram.org/bots/api#sendmessage

**Comment by vjgarciag96** [comment]
Thanks for reporting! I'll add support to send messages with a channel name
