### ISSUE TITLE
Invalid response type of deleteMessage()

### ISSUE THREAD

**Issue by reopold** [kotlin-telegram-bot/kotlin-telegram-bot#121]
The response type of the `deleteMessage()` function should be `Call<Response<Boolean>>`, 
not `Call<Response<Message>>`

**Expected behavior**
No errors when call `deleteMessage() `

**Actual behavior**
Responce error when call `deleteMessage() `

**To Reproduce**
`deleteMessage(c_id, m_id)`

**Screenshots/Traceback**
Response:
_nov 04, 2020 2:38:04 AM okhttp3.internal.platform.Platform log
INFO: {"ok":true,"result":true}_

**Possible solutions**
Change `<Message>` to `<Boolean>`

**Comment by reopold** [comment]
From Telegram API:
_"Returns True on success."_

**Comment by vjgarciag96** [comment]
Thanks for the report @reopold! I'll take a look to it

**Comment by vjgarciag96** [comment]
Fixed in https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/122 @reopold!
