### ISSUE TITLE
[Help wanted] Webhook setup

### ISSUE THREAD

**Issue by Defuera** [kotlin-telegram-bot/kotlin-telegram-bot#125]
Hi, I'm pretty sure everything working as expected, and I just missing something. Will appreciate help.

I'm trying to make my bot work with webhook, but do not get updates

What I've done.

1. In code setup webhook and start it
```
    private val bot: Bot = bot {
        token = BOT_TOKEN

        webhook {
            url = "https://a1efa8886d05.ngrok.io/$BOT_TOKEN"
        }

        dispatch {
            text { bot, update -> println(update.message?.text) }
       }
    }

bot.startWebhook()
```

2. Run ngork on port 80
![image](https://user-images.githubusercontent.com/1181883/99260832-3519a300-281c-11eb-9ecc-55a97057d087.png)

3. I expect when I send message to the bot it will be printed to the terminal. But I never receive the message.

Is there's something obvious I'm doing wrong?
Is there a way to specify a port OkHttp is listening to?

**Comment by Defuera** [comment]
Ok, nevermind, I've figured I have to run a server to receive incoming connecitons 😆

**Comment by vjgarciag96** [comment]
Is everything fine then? 

Let me know so we can close the issue if there are no problems or doubts.

**Comment by vjgarciag96** [comment]
Closing it, feel free to reopen it if you find additional problems
