### ISSUE TITLE
Dependency is not resolving.

### ISSUE THREAD

**Issue by Takshaksh** [kotlin-telegram-bot/kotlin-telegram-bot#129]
**Expected behavior**
Added it in the build.gradle
implementation 'com.github.seik.kotlin-telegram-bot:telegram:6.0.0'

It doesn't seem to be work properly.
Classes are not importing.

**Comment by vjgarciag96** [comment]
Hey @Takshaksh,

the package name changed and also the coordinates of the library. So now you should add the next to make it work:

```kotlin
implementation 'io.github.kotlin-telegram-bot.kotlin-telegram-bot:telegram:x.y.z'
```
