### ISSUE TITLE
No way to send single media

### ISSUE THREAD

**Issue by mmokeev** [kotlin-telegram-bot/kotlin-telegram-bot#132]
There is no way to send single media - always will get exception `media groups must include 2-10 items`.
Even the usage examples contain an incorrect example under `command ("mediaGroup")`. Maybe there is some workaround?

**Comment by vjgarciag96** [comment]
Hey @mmokeev!

What type of media do you want to send?

The `sendMediaGroup` operation is meant to be used to send media groups, which by definition are composed by two or more media elements.

If you want to send single items you'll have to find the proper operation for it. For example, to send a photo, you'll need to use the `sendPhoto` operation; to send a sticker, you'll need to use the `sendSticker` operation, and so on.

It's true that the sample is broken, I'll fix it!

Thanks for the report 🙂

**Comment by mmokeev** [comment]
Thanks for advice! I have used the above methods successfully :)
