### ISSUE TITLE
Getting into a loop

### ISSUE THREAD

**Issue by sinadarvi** [kotlin-telegram-bot/kotlin-telegram-bot#140]
**Expected behavior**
there is a `message` block inside the `callbackQuery(A)`. inside that `message` block we ask yes or no question with `InlineKeyboardButton`. for example, if the user chooses yes, it will go to `callbackQuery(B)`. but if chooses no, `callbackQuery(A)` will be called again.

**Actual behavior**
The problem starts when the user chooses no for the first time. after going throw all again, if he chooses no again, `InlineKeyboardButton` will popup twice!

**To Reproduce**
```kotlin
callbackQuery("A") {
    val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
    bot.sendMessage(
        chatId = chatId,
        text = """some input""",
    )

    message {
        val inlineKeyboardMarkup = InlineKeyboardMarkup.create(
            listOf(
                InlineKeyboardButton.CallbackData(text = "no", callbackData = "A"),
                InlineKeyboardButton.CallbackData(text = "yes", callbackData = "B"),
            ),
        )
        bot.sendMessage(
            chatId = message.chat.id,
            text = """
            your choice
        """.trimIndent(),
            replyMarkup = inlineKeyboardMarkup
        )
    }
}
```

**Additional context**
I think the possibility of my code being wrong is high but there is no place to ask my question, so I asked here so maybe, maybe, there is a bug.

**Comment by vjgarciag96** [comment]
@sinadarvi:

From what I can see in that code snippet, the `message` block should be outside of the `callbackQuery` block. Otherwise, every time the code within the `callbackQuery` block is called a new message handler will be added to the bot and that will cause processing a message several times

**Comment by sinadarvi** [comment]
@vjgarciag96 

So how can I handle a message inside the `callbackQuery`? I tried to use normal `bot.sendMessage()` and fold the result. but no matter what the user responded or not the response block will be executed!

```kotlin
callbackQuery("A") {
    val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
    val result = bot.sendMessage(
        chatId = chatId,
        text = """some request, that need a response from user. for example ask for id?"""
    )

    result.fold({ response: Response<Message>? ->
            val inlineKeyboardMarkup = InlineKeyboardMarkup.create(
                listOf(
                    InlineKeyboardButton.CallbackData(text = "no", callbackData = "A"),
                    InlineKeyboardButton.CallbackData(text = "yes", callbackData = "B"),
                ),
            )
            bot.sendMessage(
                chatId = chatId,
                text = """
           is your id is ${response!!.result?.text} ?
        """.trimIndent(),
                replyMarkup = inlineKeyboardMarkup
            )
    }, {

    })
}
```

how can I achieve this?

**Comment by sinadarvi** [comment]
so, after some testing, I found out(maybe I'm wrong) `response` is not the User response message to the bot request. so in order to handle this situation, you should use `message` DSL. but as @vjgarciag96 told, by doing that, you will add it as a handler every time you enter the `callbackQuery`.

So I just Manually rewrite `MessageHandler` and every time I enter the `callbackQuery`, I check if the handler is not null, I remove it by using `removeHandler`, then I add the new one by `addHandler`.

after that, I found out that it is not in order! it means no matter where you are if you trigger a message, that block will be executed! after some digging, I found out there is no chain involved! means every time you add a handler, it just added to a list and that list will be added to a hashmap no matter what the order is!

**Comment by vjgarciag96** [comment]
@sinadarvi sorry for the delays in the response 🙏🏻, but I didn't have time to check it. 

I'll try to take a look to it tomorrow and see what's going on.

**Comment by vjgarciag96** [comment]
I'm not really sure of what you want to achieve.

I'm supposing that you want to show an inline keyboard to the user and send a message back depending on the button pressed by the user in that inline keyboard? Or what's exactly what you're trying to achieve?

If it's what I'm supposing, wouldn't a snippet like the next work?

```kotlin
    val bot = bot {
        token = ANY_TOKEN
        dispatch {
            callbackQuery("a") {
                val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
                bot.sendMessage(chatId = chatId, text = "user answered yes")
            }
            callbackQuery("b") {
                val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
                bot.sendMessage(chatId = chatId, text = "user answered no")
            }
        }
    }

    bot.startPolling()
    bot.sendMessage(
        chatId = ANY_CHAT_ID,
        text = "Testing",
        replyMarkup = InlineKeyboardMarkup.create(
            listOf(
                InlineKeyboardButton.CallbackData("yes", "A"),
                InlineKeyboardButton.CallbackData("no", "B")
            )
        )
    )
```

**Comment by sinadarvi** [comment]
maybe I wasn't able to demonstrate the scenario. imagine this:
You start the bot, then the bot asks you "how can I help you?" with a bunch of inline buttons. for example, you choose "complete my order".then the bot will ask your order id. you enter your order id. then the bot will tell you "your order id is XXXXXXX, is it right?" with two inline keyboard Buttons (yes|no). if you select no, the bot should ask your order id again till you choose yes.

**Comment by vjgarciag96** [comment]
> maybe I wasn't able to demonstrate the scenario. imagine this:
> You start the bot, then the bot asks you "how can I help you?" with a bunch of inline buttons. for example, you choose "complete my order".then the bot will ask your order id. you enter your order id. then the bot will tell you "your order id is XXXXXXX, is it right?" with two inline keyboard Buttons (yes|no). if you select no, the bot should ask your order id again till you choose yes.

Oh, got it. What about the next then?

```kotlin
bot {
    token = ANY_TOKEN
    dispatch {
        command("start") {
            bot.sendMessage(
                chatId = message.chat.id,
                text = "How can I help you?",
                replyMarkup = InlineKeyboardMarkup.create(
                    listOf(
                        InlineKeyboardButton.CallbackData("Just do nothing", "Nothing"),
                        InlineKeyboardButton.CallbackData("Complete my order", "CompleteOrder")
                    )
                )
            )
        }

        callbackQuery("Nothing") {
            // Do nothing
        }

        callbackQuery("CompleteOrder") {
            val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
            bot.sendMessage(
                chatId = chatId,
                text = "Is your order id XXXXX?",
                replyMarkup = InlineKeyboardMarkup.create(
                    listOf(
                        InlineKeyboardButton.CallbackData("Yes", "OrderIdCorrect"),
                        InlineKeyboardButton.CallbackData("No", "OrderIdIncorrect")
                    )
                )
            )
        }

        callbackQuery("OrderIdCorrect") {
            val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
            bot.sendMessage(chatId = chatId, text = "Awesome, let's complete it then")
        }

        callbackQuery("OrderIdIncorrect") {
            val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
            bot.sendMessage(
                chatId = chatId,
                text = "Is your order id YYYYY?",
                replyMarkup = InlineKeyboardMarkup.create(
                    listOf(
                        InlineKeyboardButton.CallbackData("Yes", "OrderIdCorrect"),
                        InlineKeyboardButton.CallbackData("No", "OrderIdIncorrect")
                    )
                )
            )
        }
    }
}.startPolling()
```

**Comment by sinadarvi** [comment]
@vjgarciag96 the problem is that you still don't ask the User for the order id! how about, you ask for the order id inside `CompleteOrder` so after the user entered an order id, the bot tells "Is your order id XXXXX?" with inline keyboard markup?

**Comment by vjgarciag96** [comment]
So... I guess you can implement that in several different ways. Would the next snippet do what you want to achieve (I guess you can just filter out things in the `message` handler when you are not interested on them):

```kotlin
sealed class OrderProcessState {
    object NotStarted : OrderProcessState()
    object AskingForOrderId : OrderProcessState()
    data class OrderIdReceived(val orderId: Int) : OrderProcessState()
    data class Completed(val order: Int) : OrderProcessState()
}

var orderProcessState: OrderProcessState = NotStarted

bot {
    token = ANY_TOKEN
    dispatch {
        command("start") {
            bot.sendMessage(
                chatId = message.chat.id,
                text = "How can I help you?",
                replyMarkup = InlineKeyboardMarkup.create(
                    listOf(
                        InlineKeyboardButton.CallbackData("Just do nothing", "Nothing"),
                        InlineKeyboardButton.CallbackData("Complete my order", "AskForOrderId")
                    )
                )
            )
        }

        callbackQuery("Nothing") {
            // Do nothing
        }

        callbackQuery("AskForOrderId") {
            val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
            orderProcessState = AskingForOrderId
            bot.sendMessage(
                chatId = chatId,
                text = "What is your order id?"
            )
        }

        callbackQuery("OrderIdConfirmed") {
            val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
            bot.sendMessage(chatId = chatId, text = "Awesome, order confirmed!")
        }

        message {
            when (orderProcessState) {
                NotStarted -> Unit // Ignore messages in this state
                is AskingForOrderId -> {
                    val orderId = message.text?.toInt() ?: return@message
                    orderProcessState = OrderIdReceived(orderId = orderId)
                    bot.sendMessage(
                        chatId = message.chat.id,
                        text = "Can you confirm your order id is $orderId?",
                        replyMarkup = InlineKeyboardMarkup.create(
                            listOf(
                                InlineKeyboardButton.CallbackData("Yes", "OrderIdConfirmed"),
                                InlineKeyboardButton.CallbackData("No", "AskForOrderId")
                            )
                        )
                    )
                }
                is OrderIdReceived -> Unit // Ignore messages in this state
                is OrderIdConfirmed -> Unit // Ignore messages in this state
            }
        }
    }
}.startPolling()
```

**Comment by sinadarvi** [comment]
that was interesting! I didn't think of this simple way of handling it. I was thinking of handling it in a chaining model way. but this will do it too! thanks.

closing this issue.
