### ISSUE TITLE
Message handlers priorities and short circuiting

### ISSUE THREAD

**Issue by v1ctor** [kotlin-telegram-bot/kotlin-telegram-bot#141]
Hi all,
I'm currently working on a bot which should support multiple session-based commands. I have my message handlers organized in this way:
```kotlin
dispatch {
                command("start") {
                    sendWelcome(message.chat.id)
                }
                command("find_mentors") {
                    val session = FindMentorsSession(mentorManager)
                    startSession(session, message.chat.id)
                }
                command("subscribe") {
                    val session = SubscribeSession()
                    startSession(session, message.chat.id)
                }
                text {
                    if (!text.startsWith("/")) {
                        val chatId = message.chat.id
                        handleUpdate(chatId, update)
                    }
                }
                callbackQuery {
                    val chatId = callbackQuery.message?.chat?.id ?: return@callbackQuery
                    handleUpdate(chatId, update)
                }
            }
```
The idea is that command handlers will create a new session while catch-all text and callback query handlers will forward update to the proper session.

The problem is that I have to filter out all the messages which start with / from text handler otherwise the message like `/subscribe` will be processed twice, once as command and again as a text message.
```kotlin
...
                    if (!text.startsWith("/")) {
...
```

My idea is to replace message handlers in the dispatcher from HashMap to the list to support a constant order of the handlers in the dispatcher, and also allow handlers to "consume" updates. It means that if one of the handlers consumed an update none of the handlers after that will get this update at all.

I'm quite happy to do it myself, I just want to get an early feedback on this idea before doing it.

Thanks in advance!

**Comment by v1ctor** [comment]
@seik  please reassign it back to me if you're happy for me to do it.

**Comment by vjgarciag96** [comment]
Hi @v1ctor! 

To filter out command messages you can also use the `message` handler with a `Text` filter instead of the `text` one:

```kotlin
dispatch {
    message(Filter.Text) {
        handleUpdate(message.chat.id, update)
    }
}
```

The idea sounds really interesting to me, happy for you to work on it! You can assign me as reviewer once the PR is ready for review 🙂
