### ISSUE TITLE
Restricting command to users

### ISSUE THREAD

**Issue by LivingWithHippos** [kotlin-telegram-bot/kotlin-telegram-bot#143]
Hello, I like to restrict commands/the whole bot to a user. I've read the various issues and examples but I can't find how to do it. What I found out:

- Filter.User(user id) should be the right filter 
- command accept a handleCommand but I don't know how to implement it
- I could just do a  if (this.message.from!!.id==123L) but hey, we have filters

I'm on 6.0.2

**Comment by vjgarciag96** [comment]
Unfortunately there's no built-in way to restrict the whole bot for a user, but we can do that at the level of message handlers by using filters.

If I understood what you want to achieve properly, let's suppose that you want to restrict a user with id 123 from executing any command.

We could achieve that by using the next:

```kotlin
bot {

    token = "ANY_TOKEN"

    dispatch {
        message(Filter.Command and !User(123L)) {
            // this is only executed when the bot receives a command that doesn't come from user 123
        }
    }
}.startPolling()
```

Is that what you are looking for? @LivingWithHippos

**Comment by LivingWithHippos** [comment]
Almost, I want to let the user lock down my bot optionally to be used by a single user.  Also, if a whitelisted user id is not added, I want the bot to accept commands for everyone. Following your tip I wrote this:

```kotlin
// injecting the value from the environment with Koin
private val whitelistedUser: Long = getKoin().getProperty<String>("WHITELISTED_USER")?.toLongOrNull() ?: 0

dispatch {
    message(Filter.Command and (if (whitelistedUser > 10000) Filter.User(whitelistedUser) else Filter.All)) {
        command("help") {
          bot.sendMessage(chatId = message.chat.id, text = helpMessage, parseMode = ParseMode.MARKDOWN)
        }
    }
}

```

And while the permission part works, the commands are executed as if they were repeated multiple times -> if I write /help once it throws a message, the second time it works twice, the third time I get three messages etc. I probably am not supposed to nest message and command, or maybe I discovered a bug? It can be reproduced with this:

```kotlin
dispatch {
message(Filter.Command) {
                    command("help") {
                        bot.sendMessage(chatId = message.chat.id, text = "Helping")
                    }
                }
}
```

Aside from that, if I'd remove the nested command(), how would I check for them?

**Comment by vjgarciag96** [comment]
If you nest a message handler within a command handler, every time the command block is executed a new message handler will be added and therefore the message block will be executed n times - that's expected.

We should probably add a filter to the library to filter messages by command text (looks like it will be handy). In the meantime, there are several alternatives to achieve that. For example, you could use a `Custom` filter.

```kotlin
dispatch {
    val helpCommandFilter = Filter.Custom { text?.startsWith("/help") ?: false }
    val userFilter = if (whitelistedUser > 10000) Filter.User(whitelistedUser) else Filter.All
    message(helpCommandFilter and userFilter) {
        bot.sendMessage(chatId = message.chat.id, text = "helpMessage", parseMode = ParseMode.MARKDOWN)
    }
}
```

Wouldn't that be enough for what you want?

**Comment by LivingWithHippos** [comment]
Yes this way it's working thanks. A couple of notes:

-  since message has no args variable I just copied the regex to get the arguments from `CommandHandleCommandHandlerEnvironmentProxy` -> `val args = message.text?.split("\\s+".toRegex())?.drop(1) ?: emptyList()` to get them

- text?.startsWith("/download") will also trigger commands such as /downloadList. We can use other checks for example with split or regexes:

```kotlin
Filter.Custom { ((text?:"").split("\\s").firstOrNull() ?: "") == "/download" }
```
