### ISSUE TITLE
Bowling animation for the random dice

### ISSUE THREAD

**Issue by vjgarciag96** [kotlin-telegram-bot/kotlin-telegram-bot#145]
There's support for a new animation for the random dice. 

This time it's the bowling emoji https://emojipedia.org/bowling/.

It would be basically doing the same we did in https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/119/files, but for the bowling emoji.

**Comment by ShrillShrestha** [comment]
Hi @vjgarciag96, I am currently learning to contribute to open source. I feel like this is a good issue to work with. I would like to try it. So, this issue deals with working on the same files that were in https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/119/files doing the same changes. Am I right?

**Comment by vjgarciag96** [comment]
Hi @ShrillShrestha!

I'm happy for you to work on the issue 🙂. Yes, you're right, it's about working on the same files that were in that PR doing the same changes but to add a different emoji in this case. 

Let me know if you need help with anything!

**Comment by ShrillShrestha** [comment]
Thanks, @vjgarciag96. I will work on this. If there are any questions, I will let you know. :)
