### ISSUE TITLE
Add unpinAllChatMessages method

### ISSUE THREAD

**Issue by vjgarciag96** [kotlin-telegram-bot/kotlin-telegram-bot#155]
A new method `unpinAllChatMessages` was added in Telegram Bot Api 5.0.

>Added the method unpinAllChatMessages, which can be used to unpin all pinned messages in a chat.

https://core.telegram.org/bots/api#unpinallchatmessages

We should add support for this new method.

**Comment by vjgarciag96** [comment]
Closed by https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/173

**Comment by xahon** [comment]
Why doesn't this method work for bot's private chat?
I wanted to make a bot that is able to unpin all messages and pin a single one to create a text-game bot, that'll update that message to reflect the game status when game state changes somehow
