### ISSUE TITLE
Add google_place_id and google_place_type to several classes and methods

### ISSUE THREAD

**Issue by vjgarciag96** [kotlin-telegram-bot/kotlin-telegram-bot#166]
The fields `google_place_id` and `google_place_type` were added to the classes `Venue`, `InlineQueryResultVenue` and `InputVenueMessageContent` and the optional parameters `google_place_id` and `google_place_type` were added to the method `sendVenue` in Telegram Bot Api 5.0.

https://core.telegram.org/bots/api#venue
https://core.telegram.org/bots/api#inlinequeryresultvenue
https://core.telegram.org/bots/api#inputvenuemessagecontent
https://core.telegram.org/bots/api#sendvenue

We should add these new fields and parameters.

**Comment by seik** [comment]
Fixed in #234
