### ISSUE TITLE
Kotlin Native Support

### ISSUE THREAD

**Issue by dhalucario** [kotlin-telegram-bot/kotlin-telegram-bot#209]
Does this library support Kotlin Native?

**Comment by naftalmm** [comment]
Nope, it's not a multiplatform project. It heavily relies on JVM stdlib and other java libraries

**Comment by dhalucario** [comment]
I don't know if the answer in this issue is enough, but you might want to add this to the readme file. But since my question is answered I will close this issue. Thank you.
