### ISSUE TITLE
Bot sending duplicates

### ISSUE THREAD

**Issue by NicolaM94** [kotlin-telegram-bot/kotlin-telegram-bot#257]
Hello everyone!
I'm a newcomer for Telegram bot programming and I'm not really sure if this is a bug or it's me doing something wrong. If that's the case forgive me!

I'm trying to create a bot which simply returns data from a json file, filtering and manipulating it. Each json has a tag called "level", so I wrote a "search by level" callback query. Once is fired, this callback sends a message to ask the user to input the level (from 0 to 9). Then the bot simply reads the json and filters the output to send as a message.

The problem is that it sends duplicates while the callback is fired more than once. If you fire it 2 times, it will send 2 messages and the third time it will send 3 messages, and so on.

Here's the code:

```
 val holder = deserializeSpells("/home/nicola/Desktop/formattedFile.json")
 val bot = bot {
        dispatch {
            command("start") {
                bot.sendMessage(ChatId.fromId(update.message!!.chat.id),"<b><i>Benvenuto in WizardBook!</i></b>", parseMode = ParseMode.HTML)
                bot.sendMessage(ChatId.fromId(update.message!!.chat.id),"Ti aiuterò a trovare gli incantesimi!")
                val replyMarkup = InlineKeyboardMarkup.create(
                    listOf(
                        InlineKeyboardButton.CallbackData("Cerca per livello","bylevel"),
                        InlineKeyboardButton.CallbackData("Cerca per classe","byclass")),
                    listOf(
                        InlineKeyboardButton.CallbackData("Cerca per scuola","byschool"),
                        InlineKeyboardButton.CallbackData("Cerca per nome (o un pezzo)","byname")),
                    listOf(InlineKeyboardButton.CallbackData("Cerca per nome (preciso)","byreference")),
                    listOf(InlineKeyboardButton.CallbackData("La magia del giorno!","byday")),
                    listOf(InlineKeyboardButton.CallbackData("Contatti","bycontacts"))
                )
                bot.sendMessage(ChatId.fromId(message.chat.id),"Scegli il metodo di ricerca", replyMarkup = replyMarkup)
            }

            callbackQuery ("bylevel") {
                val chatId = update.callbackQuery?.message!!.chat.id
                bot.sendMessage(ChatId.fromId(chatId),"Che livello stai cercando? <u>(Da 0 a 9)</u>", parseMode = ParseMode.HTML)
                text {
                    var out :String = ""
                    holder.forEach {
                        if (it.level == text) out+= "\n${it.name}\n<i><u>Lvl. ${it.level} Classi ${it.combat}</u></i>"
                    }
                    bot.sendMessage(ChatId.fromId(chatId),out, parseMode = ParseMode.HTML)
                }
            }
        }
    }
    bot.startPolling()
```
Maybe it's me not understanding how to properly handle updates?
Thanks a lot!

**Comment by vjgarciag96** [comment]
I think this behaviour is intended. Every time you call `text { }`, you are adding a handler for text messages. If you call `text { }` every time you get a specific answer from the callback, you'll have as many handlers as answers (previous handlers are kept unless you remove them) and thus the duplicates and so on.

I think that if you put the `text {}` call outside of the callback query lambda you'll get the behaviour that you expect. If what you want is to add this text handler ad-hoc once the users has selected an option in the first keyboard, there are a few of options to do it with the current APIs. For example, using another inline keyboard to let the user choose between 0-9 as you have done for the fist interaction, having a text handler outside of the callbackQuery that is only active once you have received the response, etc...

I had never considered this use case, but it could be interesting to offer an API in the library that allows you get the behaviour you'd like here, i.e. a text handler that processes a single text message and then is destroyed, I'll probably give that a thought. 

Thanks for reporting your issue and asking @NicolaM94, and let me know if you need more help with that.

**Comment by NicolaM94** [comment]
Having a library like that would be awesome, one could build much complex commands and queries. Up until that Christmas present though, I'll try to work something around implementing one of the solutions you guys suggested and poke it around to see the behavior, maybe manually closing the text handler each time. Thanks a lot!

**Comment by lifestreamy** [comment]
@NicolaM94 good day to you, gentleman, would you kindly answer to my issue that is mentioned this one in? My project depends on this behaviour and sadly, if I can't get removeHandler() to work, I am considering choosing another library. Thank you.

**Comment by lifestreamy** [comment]
I think I've mistakenly menthioned the wrong user. Here we go @seik @vjgarciag96
