### ISSUE TITLE
 bot.setMyCommands() does not successfully add camelCase commands

### ISSUE THREAD

**Issue by lifestreamy** [kotlin-telegram-bot/kotlin-telegram-bot#259]
```
bot.setMyCommands(listOf(BotCommand("userButtons","User Buttons")))
bot.getMyCommands().fold({ list ->
                    list.forEach {
                        print("command /${it.command} description ${it.description}")
                    }
                },
                    {}
                )
```
**Expected behavior**
output:
`command /userButtons description User Buttons`
**Actual behavior**
output:
 ``
**To Reproduce**
```
bot.setMyCommands(listOf(BotCommand("userButtons","User Buttons")))
bot.getMyCommands().fold({ list ->
                    list.forEach {
                        print("command /${it.command} description ${it.description}")
                    }
                },
                    {}
                )
```

**Screenshots/Traceback**

**Possible solutions**
Fix something with Json Serialization

**Additional context**
any command added in lowerCamelCase/CamelCase is not getting added. After being added in full-low-case and being added again in camelCase the result is shown as if it retained original full-low-case value. If not added previously in full-low-case, then no command is added

**Comment by vjgarciag96** [comment]
Thanks for reporting @lifestreamy! However, I don't think that's a problem in the library but a limitation on Telegram's commands. The documentation says:

```A command must always start with the '/' symbol and may not be longer than 32 characters. Commands can use latin letters, numbers and underscores.```

They don't explicitly say lowercase latin letters, but by the underscores I imagine they want to enforce snake_case as the standard for the commands. If you try to add your commands using BotFather (https://telegram.me/BotFather) you'll run into the same error when you use an uppercase letter. 

Let me know if this makes sense to you.

**Comment by lifestreamy** [comment]
It makes sense now, thank you!
