### ISSUE TITLE
Lib disappeared on jitpack

### ISSUE THREAD

**Issue by Mr3zee** [kotlin-telegram-bot/kotlin-telegram-bot#269]
![telegram-cloud-document-2-5370752493640752148](https://user-images.githubusercontent.com/58986158/196912082-67a2fa3e-7854-497b-80fc-f42836d92c58.jpg)
<img width="422" alt="image" src="https://user-images.githubusercontent.com/58986158/196912277-8900efb1-7fc5-4e81-9eb0-810e3efc3c3b.png">
We can not pull latest release from jitpack

**Comment by vjgarciag96** [comment]
@Mr3zee I was able to pull the library via jitpack now. I can also find it fine here https://jitpack.io/#kotlin-telegram-bot/kotlin-telegram-bot/6.0.7. Do you have the jitpack repository configured properly in the project?
