### ISSUE TITLE
Is it possible to send a new message outside dispatcher?

### ISSUE THREAD

**Issue by SpeedFire0** [kotlin-telegram-bot/kotlin-telegram-bot#283]
**Expected behavior**
I want to send a message from my Bot into the group when something happens in the app, not just as a reply to the user's message.

**Actual behavior**
This doesn't work from my OnClick method:
```
telegramBot.sendMessage(chatId = telegramChatId,
                text = "user clicked the button",
                allowSendingWithoutReply = true)
```

**To Reproduce**
See the code above

**Screenshots/Traceback**
-

**Possible solutions**
-

**Additional context**
-

**Comment by JcMinarro** [comment]
@SpeedFire0 
It is currently possible.
You need to be sure your bot is allowed to send message to this group.
Could you share the log when you try to send the message?
You need to configure your bot with Log Level.
```
val telegramBot = bot {
  logLevel = LogLevel.All(LogLevel.Network.Body)
  [...]
}

telegramBot.sendMessage(chatId = telegramChatId,
                text = "user clicked the button",
                allowSendingWithoutReply = true)
```
