### ISSUE TITLE
Open `Handler` Classes to be able to extend them

### ISSUE THREAD

**Issue by JcMinarro** [kotlin-telegram-bot/kotlin-telegram-bot#286]
**Describe the solution you'd like**
Handlers Implementations are final internal classes and don't allow customizations.
Could be interesting to add extra customization to those classes. Imagine I want to create a custom `CommandHandler` that apart of check if user called the `/command`, contains a valid argument. If I could extend the `CommandHandler` class it would be as easy as:
```
val customCommand = object : CommandHandler("command", {
    // Logic to consume the update
}) {
    override fun checkUpdate(update: Update): Boolean =
        super.checkUpdate(update) &&
            update.message?.text?.contains("light") ?: false
}
```

**Implementation ideas**
Declare `Handler`'s implementation as `public open class`

**Comment by vjgarciag96** [comment]
Opening the handler checks to the public makes sense to me, I can see the use case you describe here. About the API, I'm not sure whether we should make the classes public to allow inheritance or rather public final to encourage composition for this cases. For example:

```kotlin
class MyCustomCommandHandler(
    private val exampleCommandHandler: CommandHandler,
): Handler {
    
    override fun checkUpdate(update: Update): Boolean {
        return exampleCommandHandler.checkUpdate(update) && update.message?.text == "ruka"
    }

    override suspend fun handleUpdate(bot: Bot, update: Update) {
        // do your thing
    }
}
```

I guess one downside of the composition approach is that you can't re-use existing handlers in anonymous objects which might be handy to implement your handlers "inline". We also lose the automatic validation of the handled object (i.e., for a channel post, have access to a non-null channel post object in the handle function vs having an update with a nullable channel post).

I'm also thinking of other alternatives for this, like:

* Extract the checkUpdate logic from command classes, expose that separately and keep handlers hidden . What we lose here is the automatic validation of the handled object that I mentioned before. I wonder if we could leverage contracts here.
* Have an "extended handler", which basically takes any handler and an extra predicate and would allow us to implement the same use case you mention. For example:

```kotlin
class ExtendedHandler(
    private val delegateHandler: Handler,
    private val predicate: (Update) -> Boolean,
): Handler by delegateHandler {
    
    override fun checkUpdate(update: Update): Boolean {
        return delegateHandler.checkUpdate(update) && predicate(update)
    }
}
```

And then the API to build one of these could be:

```kotlin
infix fun Handler.requires(predicate: (Update) -> Boolean): Handler {
    return ExtendedHandler(this, predicate)
}
```

Which would look similar to your proposal:

```kotlin
CommandHandler("whatever") {
        
} requires { it.message?.text == "light" }
```

This option would have same benefits as opening the classes but without opening them. It would also save the consumer from having to do the `super.checkUpdate` part.

I'm just worried that making the classes open could lead to a misuse of them or a too complex API (as in, you need to know about the library implementation details to do this) and wonder if we can do better.

Any thoughts on this @JcMinarro?

**Comment by JcMinarro** [comment]
I see your point and I like the idea to have an `ExtendedHandler`.
The API looks good with this approach. Let me think about it and try to apply it to my PR.
I think we will need to improve the rest of extension functions to add handlers to the bot as well

**Comment by vjgarciag96** [comment]
> I have been reviewing our extensions functions and it is not easy/intuitive to add the required predicate into them.
The extensions create and add the handlers into the Dispatcher in one shot, so we can't concatenate them either.
So, for now, I left those extension functions as they were, but added the ExtendedHandler class and made Handlers public final classes

Sounds good to me for now. I'll review that now, thanks!
