### ISSUE TITLE
Admin case

### ISSUE THREAD

**Issue by ivanbeshka** [kotlin-telegram-bot/kotlin-telegram-bot#295]
I work at telegram bot with multiply access to commands
In my case one command can be called from admin or common user

My solution:
```kotlin
command("start", adminTelegramId, { 
        //common user case 
    }, {
        //admin case 
    }
)
```
or
```kotlin
command("start", adminTelegramId) {
    //admin case 
}
```

Thanks in advance for your reply!

**Comment by LennyLizowzskiy** [comment]
But you can do it easily with your own function
