### ISSUE TITLE
Where is ChatMemberUpdated?

### ISSUE THREAD

**Issue by TuringHero** [kotlin-telegram-bot/kotlin-telegram-bot#296]
**Expected behavior**
When i handle newChatMembers, I want to know the invite link the user use
**Actual behavior**
I find a class name ChatMemberUpdated in other SDK and in this pr https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/236, but not in the latest version

**Comment by JcMinarro** [comment]
Added on https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/301
