### ISSUE TITLE
Add example for Markdown handling

### ISSUE THREAD

**Issue by asm0dey** [kotlin-telegram-bot/kotlin-telegram-bot#35]
It's possible to send markdown to bot, but currently I can't see any way to handle it. If that's possible — could you please write example of usage?

**Comment by seik** [comment]
Hi @asm0dey, @vjgarciag96 just added an example showing hot to handle markdown, check it out! https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/41
