### ISSUE TITLE
Downloading files

### ISSUE THREAD

**Issue by sssemil** [kotlin-telegram-bot/kotlin-telegram-bot#37]
In the current version it is not possible to dowload files, like photos or anything else.

Impement the 'file' call, than can use the File returned by the [getFile](https://core.telegram.org/bots/api#getfile) call.

No alternatives I can see, except for dowloading it manually, in your own code.

Just implement dowloading based on File object with `https://api.telegram.org/file/bot<token>/<file_path>` link, as described in the API docs,

**Comment by rundoom** [comment]
Seems like this issue can be closed by 9889665109fd9229eaed57ac0d84b36816dc4b87
