### ISSUE TITLE
Inconsistent method signature in sendPhoto

### ISSUE THREAD

**Issue by FRQDO** [kotlin-telegram-bot/kotlin-telegram-bot#49]
**Expected behavior**
I can pass a photo, a caption, _and a reply markup_ to `Bot#sendPhoto`.

**Actual behavior**
The `ApiService.kt` has a field for the `reply_markup` in each `sendPhoto` function.
The `ApiClient.kt` that redirects its `sendPhoto` to the `ApiService` is oblivious to this parameter.
Therefore, the `Bot.kt` does not have this parameter, either.

**To Reproduce**
See `Bot.kt`, lines 129–159, `ApiClient.kt`, lines 135–171, and in contrast, `ApiService.kt`, lines 74–96.

**Screenshots/Traceback**
![image](https://user-images.githubusercontent.com/5584852/73498764-81dfda80-43be-11ea-9366-ebc5e6dbd195.png)

**Possible solutions**
Probably including the parameter was just forgotten in the other two files?

**Comment by vjgarciag96** [comment]
Hi @FRQDO! Thanks for reporting the issue. The problem has been fixed by @elihun in this PR -> #48. Just for your interest. I'll close the issue.

**Comment by FRQDO** [comment]
Great news, thanks!
