### ISSUE TITLE
Disable logging by default

### ISSUE THREAD

**Issue by vjgarciag96** [kotlin-telegram-bot/kotlin-telegram-bot#82]
The current implementation of the bot has the logging enabled by default. I think it could be a good idea to have it disabled by default, so only the people who need it have to enable it and the people that don't want it don't have to disable it.

This change is really easy, we just have to set the default bot's `logLevel` to `HttpLoggingInterceptor.Level.NONE`.

It would be also nice to add a bit of documentation about how to enable logging and indicating that logging is disabled by default.

Another thought I have, maybe out of scope of the pull request, is to create an enum in the library to represent the different log levels and use it instead of the OkHttp's one to decouple this part from the library. The biggest trouble with this change is that it's a breaking API change (maybe not really a big trouble if people don't use `logLevel`, but I'm not really sure of the impact of the change. Anyways, the migration to the new `logLevel` would be straightforward)

**Comment by seik** [comment]
Makes sense to me.

And a 👍 for abstracting Okhttp from our library. Even if it is a breaking change, maybe not a lot of people are modifying the default level of logging. And if it is, is a one line change.
