### ISSUE TITLE
Create a handler to allow working with commands as messages

### ISSUE THREAD

**Issue by vjgarciag96** [kotlin-telegram-bot/kotlin-telegram-bot#88]
Currently, the library has a handler for commands (`CommandHandler`) to let us passing functions to it that will be executed every time a command is received. 

The functions we can pass to the mentioned handler have the signature `(Bot, Update, List<String>) -> Unit` or `(Bot, Update) -> Unit`. Therefore we can define something like the next:

```kotlin
bot {
    // config stuff
    dispatch {
        command { bot, update, commandArgs ->
            // do whatever we want with the received update
        }
    }
}
```

Some common use cases imply the bot sending an answer to the conversation that originated the update. To interact with a conversation it's needed to know its `chatId` or `channelUsername`. For a command, the current way of implementing a use case like that would be doing something like the next:

```kotlin
bot {
    // config stuff
    dispatch {
        command { bot, update, commandArgs ->
            val chatId = update.message?.chatId ?: error("Unreachable path")
            // do whatever you want with the chat id
        }
    }
}
```

However, we know that when a command is received we can assume the `message` field is not null because a command is a message. Therefore, we could avoid writing the useless code checking that the `message` field of the `update` object correspondent to a command is not null (in a more elegant way than using the not null operator !). The ideal thing we could have would look like the next:

```kotlin
bot {
    // config stuff
    dispatch {
        command { bot, command: Message, commandArgs ->
            val chatId = command.chatId // -> we can now access chat id as a a mandatory field
            // do whatever you want with the chat id
        }
    }
}
```

Taking a look to the `CommandHandler` and `Dispatcher` files would be a really good starting point for the task.

**Comment by seik** [comment]
Addressed in #91

⊂(◉‿◉)つ
