### ISSUE TITLE
6.0.0 version and breaking changes

### ISSUE THREAD

**Issue by seik** [kotlin-telegram-bot/kotlin-telegram-bot#93]
Since the last version at least 2 breaking changes have been introduced:
#82 and #91 (not merged at the moment but approved).

Maybe it's time to create a major version with big changes and release all breaking changes at the same time.

I opened this issue to plan the next release and to ask if there are any other changes you have always wanted to introduce but were afraid because of breaking too many things.

**Comment by vjgarciag96** [comment]
I agree with you, the breaking API changes should mean a new major version.

Also agree that we should include other breaking changes that we were afraid of adding now that we're going to increase the major version number. 

In the top of my mind I'd say that migrating all the other dispatcher functions (like `message`, `text`, `callbackQuery`, etc...) to the same approach we've implemented for `command` (https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/91) would be a good one (for consistency with the other changes and to improve the functionality provided). That shouldn't be a really hard or time consuming task (I could probably work on it and finish it this weekend).

There is nothing else in the top of my mind, but if I took a look to the project I may come up with some other changes. However, I wouldn't be able to take that look until the weekend. Is it ok from your side to wait until then?

**Comment by seik** [comment]
I'm totally fine with that, we should take all the time we need to do this. 😄

**Comment by vjgarciag96** [comment]
Cool!

I have created an issue for the wish mentioned in the previous comment -> https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/issues/96

Also, after taking a look to the project, I don't have anything else I would like to change that will mean a breaking API change. 

So, once implemented the issue mentioned in the comment (and if there is not anything else) we could create the new major release.

**Comment by snail-bob** [comment]
Hello, guys!

When do you plan to release 6.0.0 version?

**Comment by vjgarciag96** [comment]
We've merged the main PR for this release today https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/103, so we'll probably release the new version soon

**Comment by vjgarciag96** [comment]
Still want to add a change related with the issue https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/issues/113 (work in progress) that would slightly break the API compatibility in some parts of the library, so it would be nice to include it in 6.0.0 too

**Comment by vjgarciag96** [comment]
I'm going to release this now

**Comment by vjgarciag96** [comment]
Finally released https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/releases/tag/6.0.0!

Closing the issue
