### ISSUE TITLE
Telegram passport support

### ISSUE THREAD

**Issue by odeadglaz** [kotlin-telegram-bot/kotlin-telegram-bot#94]
Hello, 
I would love to ask if you are planning to add support for telegram passport since it has been released at version `4.0`?

Thanks in advance.

**Comment by vjgarciag96** [comment]
Hey @odeadglaz! 

Yes, we want to provide full support to the Telegram Bot API from the library, therefore supporting Telegram passport is in our plans. However, I can't say anything about when we'll work on it...

For the moment, I have created an issue to keep track of this feature request and to make it visible to any possible contributor interested in working on it -> https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/issues/95

Thanks for you question!
