### ISSUE TITLE
message.media_group_id field

### ISSUE THREAD

**Issue by y9san9** [kotlin-telegram-bot/kotlin-telegram-bot#98]
**Is your feature request related to a problem? Please describe.**
I wanna handle media group with some photos, but for that case I need media_group_id field and api to get it

**Additional context**
![image](https://user-images.githubusercontent.com/46930374/89499069-112fd580-d7c8-11ea-8a2f-659639a798fd.png)

**Comment by vjgarciag96** [comment]
Hey @y9san9!!

Thanks for reporting! 

Fixed in https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/100

**Comment by y9san9** [comment]
thank you, also via your library I can handle only one update (as I know), but to handle media group, I should get all new updates and then select updates that has same media_group_id, can you implement that ? Something like
```kotlin
mediaGroup { bot: Bot, updates: List<Update> ->

}
```

**Comment by vjgarciag96** [comment]
re @y9san9: Sure, can you create a new issue explaining the feature request?
